<?php

namespace Database\Seeders;

use App\Models\School;
use App\Models\SchoolLevel;
use App\Models\Village;
use Illuminate\Database\Seeder;

class SchoolSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    $schools = [
      [
        'name' => 'MAS Raudhotut Tholibin Kembaran',
        'address' => 'Jl. Pesantren RT02 RW 07 Dukuhwaluh, Kec.Kembaran, Kab. Banyumas',
        'status' => 'SWASTA',
        'lat' => '-7.4095304',
        'lang' => '109.2704913',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'MAS',
        'village_id' => 'Dukuhwaluh',
      ],
      [
        'name' => 'MIN 3 BANYUMAS',
        'address' => 'JL. BALAI DESA KARANGSARI NO. 47 KEMBARAN KABUPATEN BANYUMAS',
        'status' => 'SWASTA',
        'lat' => '-7.4003124',
        'lang' => '109.279464',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'MIN',
        'village_id' => 'Karangsari',
      ],
      [
        'name' => 'MIS AL FALAH KARANGTENGAH',
        'address' => 'JL.RAYA KARANGTENGAH',
        'status' => 'NEGERI',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'MIS',
        'village_id' => 'Karangtengah',
      ],
      [
        'name' => 'MIS AL FATAH PURWODADI',
        'address' => 'JL.MASJID NO.1 RT03/ RW01',
        'status' => 'SWASTA',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'MIS',
        'village_id' => 'Purwodadi',
      ],
      [
        'name' => 'MIS MA`ARIF NU 1 PLIKEN',
        'address' => 'JL.RAYASOKARAJASUMBANGNO.20RT3/8PLIKEN',
        'status' => 'SWASTA',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'MIS',
        'village_id' => 'Pliken',
      ],
      [
        'name' => 'MIS MIFTAHUL HUDA LINGGASARI',
        'address' => 'JL.PONPES MAMBAUL USHULIL HIKMAH BAKUNG RT07/I LINGGASARI',
        'status' => 'SWASTA',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'MIS',
        'village_id' => 'Linggasari',
      ],
      [
        'name' => 'MIS MUHAMMADIYAH KRAMAT',
        'address' => 'JL. MASJID NO.02 DESA KRAMAT RT 5 RW 1',
        'status' => 'SWASTA',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'MIS',
        'village_id' => 'Kramat',
      ],
      [
        'name' => 'MIS RAUDHOTUL THOLIBIN KEMBARAN',
        'address' => 'DUKUHWALUH RT 02 RW 07',
        'status' => 'SWASTA',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'MIS',
        'village_id' => 'Dukuhwaluh',
      ],
      [
        'name' => 'MTsS MA`ARIF NU 1 KEMBARAN',
        'address' => 'KARANGSARI RT 3/III',
        'status' => 'SWASTA',
        'lat' => '-7.4034526',
        'lang' => '109.2813186',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'MTsS',
        'village_id' => 'Karangsari',
      ],
      [
        'name' => 'MTsS SA RAUDHOTUT THOLIBIN KEMBARAN',
        'address' => 'JL. PESANTREN RT 02 RW 07DUKUHWALUH',
        'status' => 'SWASTA',
        'lat' => '-7.4095123',
        'lang' => '109.2705459',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'MTsS',
        'village_id' => 'Dukuhwaluh',
      ],
      [
        'name' => 'SD ISLAM SINAR MENTARI',
        'address' => 'Jln. Redjo Rt 02 Rw 08 Desa Dukuhwaluh',
        'status' => 'SWASTA',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Dukuhwaluh',
      ],
      [
        'name' => 'SD N 1 DUKUHWALUH',
        'address' => 'Jl. Raden Patah N0 1',
        'status' => 'NEGERI',
        'lat' => '-7.4148657',
        'lang' => '109.2693724',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Dukuhwaluh',
      ],
      [
        'name' => 'SD N 1 LINGGASARI',
        'address' => 'Jln. Mayor Broto Siswoyo No. 2',
        'status' => 'NEGERI',
        'lat' => '-7.3951598',
        'lang' => '109.2874714',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Linggasari',
      ],
      [
        'name' => 'SD N 1 SAMBENG KULON',
        'address' => 'Jl Raya Sambeng Kulon No 5 RT 02 RW 01',
        'status' => 'NEGERI',
        'lat' => '-7.399448',
        'lang' => '109.301507',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Sambeng Kulon',
      ],
      [
        'name' => 'SD N 2 DUKUHWALUH',
        'address' => 'Dukuhwaluh',
        'status' => 'NEGERI',
        'lat' => '-7.4147446',
        'lang' => '109.2676209',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Dukuhwaluh',
      ],
      [
        'name' => 'SD N 2 PLIKEN',
        'address' => 'Jl.Imam Bonjol No. 4',
        'status' => 'NEGERI',
        'lat' => '-7.4354762',
        'lang' => '109.2880582',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Pliken',
      ],
      [
        'name' => 'SD N 3 DUKUH WALUH',
        'address' => 'Jl.sunan Bonang 10',
        'status' => 'NEGERI',
        'lat' => '-7.4125917',
        'lang' => '109.2673956',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Dukuhwaluh',
      ],
      [
        'name' => 'SD N 3 PLIKEN',
        'address' => 'Jl. Imam Bonjol No.819 Rt 03 Rw 06',
        'status' => 'NEGERI',
        'lat' => '-7.425623',
        'lang' => '109.2860209',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Pliken',
      ],
      [
        'name' => 'SD N 4 PLIKEN',
        'address' => 'Jl. Bojongsari Pliken RT 03 RW 06',
        'status' => 'NEGERI',
        'lat' => '-7.4248755',
        'lang' => '109.2841494',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Pliken',
      ],
      [
        'name' => 'SD N SAMBENG WETAN',
        'address' => 'Sambeng Wetan',
        'status' => 'NEGERI',
        'lat' => '-7.4031447',
        'lang' => '109.2917713',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Sambeng Wetan',
      ],
      [
        'name' => 'SD NEGERI 1 BANTARWUNI',
        'address' => 'Jl Perintis Kemerdekaan',
        'status' => 'NEGERI',
        'lat' => '-7.3972488',
        'lang' => '109.2656744',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Bantarwuni',
      ],
      [
        'name' => 'SD NEGERI 1 BOJONGSARI',
        'address' => 'Jln. Raya Desa Bojongsari',
        'status' => 'NEGERI',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Bojongsari',
      ],
      [
        'name' => 'SD NEGERI 1 PLIKEN',
        'address' => 'Pliken, Rt 5 Rw 2',
        'status' => 'NEGERI',
        'lat' => '-7.432389',
        'lang' => '109.2879662',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Pliken',
      ],
      [
        'name' => 'SD NEGERI 1 PURBADANA',
        'address' => 'Purbadana, Rt 05 Rw. 02',
        'status' => 'NEGERI',
        'lat' => '-7.4013987',
        'lang' => '109.2874247',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Purbadana',
      ],
      [
        'name' => 'SD NEGERI 2 BANTARWUNI',
        'address' => 'Bantarwuni',
        'status' => 'NEGERI',
        'lat' => '-7.3893904',
        'lang' => '109.2713286',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Bantarwuni',
      ],
      [
        'name' => 'SD NEGERI 2 SAMBENG KULON',
        'address' => 'Sambeng Kulon',
        'status' => 'NEGERI',
        'lat' => '-7.4102289',
        'lang' => '109.2981203',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Sambeng Kulon',
      ],
      [
        'name' => 'SD NEGERI 3 LINGGASARI',
        'address' => 'Jalan Raya Karangmiri Linggasari',
        'status' => 'NEGERI',
        'lat' => '-7.3960672',
        'lang' => '109.2807382',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Linggasari',
      ],
      [
        'name' => 'SD NEGERI KARANGSOKA',
        'address' => 'Jl. Raya Karangsoka',
        'status' => 'NEGERI',
        'lat' => '-7.4080669',
        'lang' => '109.2742748',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Karangsoka',
      ],
      [
        'name' => 'SD NEGERI KEMBARAN',
        'address' => 'Jalan Raya No. 08 Kembaran',
        'status' => 'NEGERI',
        'lat' => '-7.4122222',
        'lang' => '109.2851968',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Kembaran',
      ],
      [
        'name' => 'SD NEGERI KRAMAT',
        'address' => 'Jln. Balai Desa No. 1 Kramat',
        'status' => 'NEGERI',
        'lat' => '-7.416411',
        'lang' => '109.3116479',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Kramat',
      ],
      [
        'name' => 'SD NEGERI LARANGAN',
        'address' => 'Jln. Kecamatan No. 3 Kembaran',
        'status' => 'NEGERI',
        'lat' => '-7.4022107',
        'lang' => '109.2842289',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Kembaran',
      ],
      [
        'name' => 'SD NEGERI LEDUG',
        'address' => 'Jl. Purnawira 1',
        'status' => 'NEGERI',
        'lat' => '-7.4275214',
        'lang' => '109.2703296',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Ledug',
      ],
      [
        'name' => 'SD NEGERI TAMBAKSARI',
        'address' => 'Jln. Sunan Bonang ',
        'status' => 'NEGERI',
        'lat' => '-7.3943187',
        'lang' => '109.2632593',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Tambaksari',
      ],
      [
        'name' => 'SD UMP',
        'address' => 'Jl. Senopati No. 17 Dukuhwaluh Purwokerto',
        'status' => 'SWASTA',
        'lat' => '-7.4137314',
        'lang' => '109.2653795',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Tambaksari',
      ],
      [
        'name' => 'SDN 2 BOJONGSARI',
        'address' => 'Bojongsari, RT 05/01',
        'status' => 'NEGERI',
        'lat' => '-7.4168063',
        'lang' => '109.2793468',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Bojongsari',
      ],
      [
        'name' => 'SDN 2 LINGGASARI',
        'address' => 'Linggasari',
        'status' => 'NEGERI',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Linggasari',
      ],
      [
        'name' => 'SDN 2 PURBADANA',
        'address' => 'Purbadana, Rt 03. Rw 02',
        'status' => 'NEGERI',
        'lat' => '-7.4260281',
        'lang' => '109.2516003',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Purbadana',
      ],
      [
        'name' => 'SDN 4 DUKUHWALUH',
        'address' => 'Jl. Sunan Bonang',
        'status' => 'NEGERI',
        'lat' => '-7.4082321',
        'lang' => '109.267176',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'dukuhwaluh',
      ],
      [
        'name' => 'SDN KARANGSARI',
        'address' => 'Jln Raya Karangsari Kec. Kembaran.',
        'status' => 'NEGERI',
        'lat' => '-7.4044926',
        'lang' => '109.2816526',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'KARANGSARI',
      ],
      [
        'name' => 'SDN KARANGTENGAH',
        'address' => 'Karangtengah',
        'status' => 'NEGERI',
        'lat' => '-7.4045197',
        'lang' => '109.2802307',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Karangtengah',
      ],
      [
        'name' => 'SDN PURWODADI',
        'address' => 'Purwodadi',
        'status' => 'NEGERI',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SD',
        'village_id' => 'Purwodadi',
      ],
      [
        'name' => 'SMK KESEHATAN KESATRIAN 2 PURWOKERTO',
        'address' => 'Jl. Sunan Bonang Dukuhwaluh Kembaran',
        'status' => 'SWASTA',
        'lat' => '-7.408271',
        'lang' => '109.2659885',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SMK',
        'village_id' => 'Dukuhwaluh',
      ],
      [
        'name' => 'SMK Mulia Bakti Purwokerto',
        'address' => 'Jl. Sunan Bonang No.121 Dukuhwaluh',
        'status' => 'SWASTA',
        'lat' => '-7.4090733',
        'lang' => '109.266483',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SMK',
        'village_id' => 'Dukuhwaluh',
      ],
      [
        'name' => 'SMKS MAARIF NU 1 KEMBARAN',
        'address' => 'PONPES MAMBAUL USHULIL HIKMAH',
        'status' => 'SWASTA',
        'lat' => '-7.4573129',
        'lang' => '109.2435044',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SMKS',
        'village_id' => 'Dukuhwaluh',
      ],
      [
        'name' => 'SMP GUNUNGJATI KEMBARAN',
        'address' => 'Jl. R. Patah 911 A',
        'status' => 'SWASTA',
        'lat' => '-7.4204435',
        'lang' => '109.2685436',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SMP',
        'village_id' => 'Ledug',
      ],
      [
        'name' => 'SMP ISLAM TERPADU NUSANTARA KEMBARAN',
        'address' => 'RT 005 RW 002',
        'status' => 'SWASTA',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SMP',
        'village_id' => 'Karangtengah',
      ],
      [
        'name' => 'SMP ISLAM WALISONGO KEMBARAN',
        'address' => 'Jl. Ponpes Mambaul Ushulil Hikmah',
        'status' => 'SWASTA',
        'lat' => '',
        'lang' => '',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SMP',
        'village_id' => 'Linggasari',
      ],
      [
        'name' => 'SMP MUHAMMADIYAH KEMBARAN',
        'address' => 'Kembaran Banyumas',
        'status' => 'SWASTA',
        'lat' => '-7.4143763',
        'lang' => '109.3099821',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SMP',
        'village_id' => 'KEMBARAN',
      ],
      [
        'name' => 'SMP NEGERI 1 KEMBARAN',
        'address' => 'Kembaran',
        'status' => 'NEGERI',
        'lat' => '-7.40856',
        'lang' => '109.2849952',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SMP',
        'village_id' => 'KEMBARAN',
      ],
      [
        'name' => 'SMP NEGERI 2 KEMBARAN',
        'address' => 'Jl. Raya Purwodadi',
        'status' => 'NEGERI',
        'lat' => '-7.4179255',
        'lang' => '109.2974625',
        'logo_photo_path' => "schools/logo/beruang.png",
        'school_level_id' => 'SMP',
        'village_id' => 'Purwodadi',
      ],
    ];

    foreach ($schools as $school) {
      if ($school['lat'] != '' && $school['lang'] != '') {
        $school['school_level_id'] = SchoolLevel::where('name', $school['school_level_id'])
          ->get()->first()->id;
        $school['village_id'] = Village::where('name', \Str::title($school['village_id']))
          ->get()->first()->id;

        School::create($school);
      }
    }
  }
}
